### ISSUE TITLE
Could not start Fleet Docker network

### ISSUE THREAD

**Issue by patriziotomato** [aschmelyun/fleet#1]
```
No Fleet network, creating one...
Could not start Fleet Docker network
```

If I'm correct, the `readme` doesn't provide me any information about where the (external) fleet network is supposed to be created from. If simply following your advices, the error above comes up.

**Comment by aschmelyun** [comment]
I probably should add some more verbose error handling to that so issues can be narrowed down. Network creation isn't in the readme because it should be handled automatically by the command.

What's the output if you run `docker network create fleet` from your terminal directly?

**Comment by patriziotomato** [comment]
This command is working perfectly fine and creates a network called fleet

But
* It is not mentioned that I should create one first
* Even though the network with name `fleet` exists, I get the same error right now!?

**Comment by patriziotomato** [comment]
My mistake was that my `art fleet:add` command was routed via alias to `sail php artisan fleet:add` which runs within the app container and of course causes trouble creating docker stuff on host machine ;)

**Comment by mreduar** [comment]
> My mistake was that my `art fleet:add` command was routed via alias to `sail php artisan fleet:add` which runs within the app container and of course causes trouble creating docker stuff on host machine ;)

How were you able to solve the problem? If we use Laravel Sail is because we don't have anything installed in our environment to run artisan commands, so in theory it should be possible to run `./vendor/bin/sail php artisan fleet:add`
